[package]
name = "httping"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
reqwest = "0.12.5"
tokio = { version = "1.40.0", features = ["full"] }
url = "2.5.2"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

