[package]
name = "httping"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
reqwest = "0.12.12"
tokio = { version = "1.44.0", features = ["full"] }
url = "2.5.4"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

